alias g=git
alias gi=g
alias gti=g
alias gt=g
alias igt=g

# Generate shorthand aliases without spaces
_generate_git_aliases() {
  echo "# This file is autogenerated. Do not modify manually." > ~/.config/rc/aliases/git_aliases.sh
  g al | sed 's/.*/alias g&="git &"/' >> ~/.config/rc/aliases/git_aliases.sh
}
_generate_git_aliases
